#!/bin/bash


eval "$(docker-machine env default)"
docker build -t edyn/logstash .
docker run --rm -ti edyn/logstash
docker run --rm -ti --entrypoint=bash edyn/logstash

# echo '{"version": "1.1","host":"example.org","short_message":"A short message that helps you identify what is going on","full_message":"Backtrace here\n\nmore stuff","level":1,"_user_id":9001,"_some_info":"foo","_some_env_var":"bar"}' | nc -w 1 -u localhost 12201
