#!/usr/bin/env bash

set -e

./setup

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
LS_HOME=/var/lib/logstash
LS_HEAP_SIZE="500m"
LS_JAVA_OPTS="-Djava.io.tmpdir=${LS_HOME}"
LS_LOG_FILE=/var/log/logstash/logstash.log
LS_USE_GC_LOGGING=""
LS_CONF_DIR=/etc/logstash/conf.d
LS_OPEN_FILES=16384
LS_NICE=19
LS_OPTS="--pipeline-workers=4"
HOME="${HOME:-$LS_HOME}"
# JAVA_OPTS="${LS_JAVA_OPTS}"

ulimit -n ${LS_OPEN_FILES}
cd "${LS_HOME}"

export PATH HOME JAVA_OPTS LS_HEAP_SIZE LS_JAVA_OPTS LS_USE_GC_LOGGING

exec s6-setuidgid logstash nice -n ${LS_NICE} /opt/logstash/bin/logstash agent -f "${LS_CONF_DIR}" ${LS_OPTS}
